--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CTMCentral/FriendsList
build-by-default: true
projects:
  FriendsList:
    type: library
    model: virion
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.4.0
      - src: DaPigGuy/Commando-4.0.0/Commando
        version: ^2.1.0
...
