name: FriendsList
main: CTMCentral\FriendsList\Main
version: 0.1.0
api: 4.0.0
description: "An in-game friends list system for PocketMine-MP servers"
authors:
 - jasonwynn10
softdepend:
 - DEVirion
 - EasyCommandAutofill