name: Friends
main: CTMCentral\Friends\Loader
version: 0.0.3
api: 4.0.0
description: "An in-game friends list system for PocketMine-MP servers"
author: CTMCentral
authors:
 - jasonwynn10
 - provsalt
permissions:
  friends:
    children:
      admin:
        description: Allows you to use adminSubCommand commands