database:
  # Edit these settings only if you choose "mysql".
  mysql:
    host: no
    # Avoid using the "root" user for security reasons.
    username: no
    password: no
    schema: friends
  # The maximum number of simultaneous SQL queries